kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: trii-dev
nodes:
  # Single control plane node
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    # Ingress Controller HTTP (NodePort mapping)
    - containerPort: 31560
      hostPort: 80
      protocol: TCP
    # HTTPS
    - containerPort: 443
      hostPort: 443
      protocol: TCP
    # ArgoCD UI (Direct NodePort)
    - containerPort: 30080
      hostPort: 8080
      protocol: TCP
    # Market Data Service
    - containerPort: 8001
      hostPort: 8001
      protocol: TCP
    image: kindest/node:v1.31.0

# Networking
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
