apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trii-dev

resources:
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: portfolio-manager
  app.kubernetes.io/component: backend-service
  app.kubernetes.io/part-of: trii-platform
  app.kubernetes.io/managed-by: argocd
  tier: business-logic

# Sync wave 3 - Business logic layer
commonAnnotations:
  argocd.argoproj.io/sync-wave: "3"
