apiVersion: v1
kind: Service
metadata:
  name: portfolio-manager-service
  namespace: trii-dev
  labels:
    app: portfolio-manager
    app.kubernetes.io/name: portfolio-manager
    app.kubernetes.io/component: service
spec:
  selector:
    app: portfolio-manager
  ports:
  - name: http
    port: 8003
    targetPort: 8003
    protocol: TCP
  type: ClusterIP
