apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trii-dev

resources:
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: analysis-engine
  app.kubernetes.io/component: backend-service
  app.kubernetes.io/part-of: trii-platform
  app.kubernetes.io/managed-by: argocd
  tier: analysis-services

# Sync wave 2 - Depends on market-data service
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
