apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: market-data-ingress
  namespace: trii-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    argocd.argoproj.io/sync-wave: "5"
spec:
  ingressClassName: nginx
  rules:
  - host: market-data.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: market-data-service
            port:
              number: 8001
