apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - frontend-service-patch.yaml

images:
  - name: backend
    newName: jaimehenao8126/trii-backend
    newTag: latest
  - name: frontend
    newName: jaimehenao8126/trii-frontend-app
    newTag: latest