apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trii-dev

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - rabbitmq/statefulset.yaml
  - rabbitmq/service.yaml
  - minio/statefulset.yaml
  - minio/service.yaml
  - postgres/statefulset.yaml
  - postgres/configmap.yaml
  - postgres/service.yaml
  - redis/statefulset.yaml
  - redis/service.yaml
  - market-data/deployment.yaml
  - market-data/service.yaml
  - market-data/ingress.yaml
  - analysis-engine/deployment.yaml
  - analysis-engine/service.yaml
  - portfolio-manager/deployment.yaml
  - portfolio-manager/service.yaml
  - ml-prediction/deployment.yaml
  - ml-prediction/service.yaml
  - ingress/trii-platform-ingress.yaml

commonLabels:
  app.kubernetes.io/name: trii-platform
  app.kubernetes.io/managed-by: argocd

images: []
