apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-data
  template:
    metadata:
      labels:
        app: market-data
        app.kubernetes.io/name: market-data
        app.kubernetes.io/component: service
