apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "market-data.fullname" . }}
  labels:
    {{- include "market-data.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "market-data.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "market-data.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.apiPort }}
              protocol: TCP
          env:
            - name: COLOMBIAN_MARKETS
              value: "{{ .Values.config.colombianMarkets }}"
            - name: API_PORT
              value: "{{ .Values.config.apiPort }}"
            - name: REDIS_HOST
              value: "{{ .Values.config.redisHost }}"
            - name: TIMESCALE_HOST
              value: "{{ .Values.config.timescaleHost }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}