apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trii-dev

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - ../postgres
  - ../redis
  - ../minio
  - ../rabbitmq
