apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml
  - service-account.yaml

commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/component: monitoring
