apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification-service.fullname" . }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "notification-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notification-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.apiPort }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.config.apiPort }}"
            - name: REDIS_HOST
              value: "{{ .Values.config.redisHost }}"
            - name: POSTGRES_HOST
              value: "{{ .Values.config.postgresHost }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}